/**
 * @type {import('stylelint').Config}
 */
const stylelintConfig = {
  extends: ['stylelint-config-standard'],
  ignoreFiles: [
    '**/.cache/**',
    '**/.next/**',
    '**/.nx/**',
    '**/.vitest/**',
    '**/build/**',
    '**/coverage/**',
    '**/dist/**',
    '**/node_modules/**',
    '**/out/**',
    '**/tmp/**',
  ],
  plugins: ['stylelint-order'],
  rules: {
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'apply',
          'config',
          'container',
          'each',
          'else',
          'if',
          'include',
          'layer',
          'mixin',
          'responsive',
          'screen',
          'source',
          'tailwind',
          'theme',
          'use',
          'utility',
          'variants',
        ],
      },
    ],
    'function-no-unknown': [
      true,
      {
        ignoreFunctions: ['theme'],
      },
    ],
    'import-notation': [
      'string',
      {
        ignoreImportLocations: ['tailwindcss'],
      },
    ],
    'no-descending-specificity': null,
    'no-empty-source': null,
    'order/properties-order': [
      [
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'display',
        'flex',
        'flex-direction',
        'flex-wrap',
        'align-items',
        'justify-content',
        'gap',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'margin',
        'padding',
        'border',
        'border-radius',
        'background',
        'color',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'text-align',
        'opacity',
        'visibility',
        'transition',
        'transform',
        'cursor',
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
    'selector-class-pattern': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global', 'local'],
      },
    ],
  },
}

export default stylelintConfig
