/** @type {import('stylelint').Config} */
const stylelintConfig = {
  extends: ['stylelint-config-standard'],
  ignoreFiles: [
    '**/.next/**',
    '**/.nx/**',
    '**/build/**',
    '**/coverage/**',
    '**/dist/**',
    '**/node_modules/**',
    '**/out/**',
  ],
  plugins: ['stylelint-order'],
  rules: {
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'apply',
          'layer',
          'responsive',
          'screen',
          'source',
          'tailwind',
          'theme',
          'utility',
          'variants',
        ],
      },
    ],
    'no-descending-specificity': null,
    'no-empty-source': null,
    'order/properties-order': [
      [
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'display',
        'flex',
        'flex-direction',
        'flex-wrap',
        'align-items',
        'justify-content',
        'gap',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'margin',
        'padding',
        'border',
        'border-radius',
        'background',
        'color',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'text-align',
        'opacity',
        'visibility',
        'transition',
        'transform',
        'cursor',
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
    'selector-class-pattern': [
      '^[a-z][a-zA-Z0-9]*$|^[a-z][a-z0-9-_]*[a-z0-9]$',
      {
        message: 'Use camelCase or kebab-case for CSS class names (CSS Modules compatible)',
      },
    ],
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global', 'local'],
      },
    ],
  },
}

export default stylelintConfig
